name: Tests

on: 
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * * 0'  

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4]
        scout: ["8.*", "9.*"]
        dependency-version: [prefer-stable, prefer-lowest]
        include:
          - scout: "^9.0"
            php: 8.0
            dependency-version: "prefer-lowest"
          - scout: "^8.5"
            php: 8.0
            dependency-version: "prefer-lowest"
          - scout: "^8.0"
            php: 7.2
            dependency-version: "prefer-lowest"
          - scout: "^8.0"
            php: 7.3
            dependency-version: "prefer-lowest"
          - scout: "^9.0"
            php: 8.0
            dependency-version: "prefer-stable"
          - scout: "^8.5"
            php: 8.0
            dependency-version: "prefer-stable"
          - scout: "^8.0"
            php: 7.2
            dependency-version: "prefer-stable"
          - scout: "^8.0"
            php: 7.3
            dependency-version: "prefer-stable"

    name: PHP ${{ matrix.php }}  - Scout ${{ matrix.scout }} (${{ matrix.dependency-version }})

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-php-${{ matrix.php }}-composer-${{ matrix.scout }}-${{ matrix.dependency-version }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, zip
        coverage: pcov

    - name: Install Composer dependencies
      run: |
        composer require "laravel/scout:${{ matrix.scout }}" --no-interaction --no-update
        composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist --no-suggest

    - name: PHPUnit Testing
      run: vendor/bin/phpunit